### ISSUE TITLE
Form Controls not working

### ISSUE THREAD

**Issue by treadyaparna** [PHPOffice/PHPExcel#1051]
In my xlsm file has some buttons. After load and write the same content in another file, this buttons are not showing. Is form controls not supported by PHPExcel?

**Comment by MarkBaker** [comment]
No it isn't supported

**Comment by treadyaparna** [comment]
Thank you for the response.

**Comment by a3aakash** [comment]
So is there is any solution to get being supported? I urgently need the solution.

**Comment by PowerKiKi** [comment]
@a3aakash, if you need it, you'll have to contribute the code to support it.

**Comment by a3aakash** [comment]
@PowerKiKi I couldn't understand your comment. And why this issue get closed if this is not been resolved at your end?

**Comment by PowerKiKi** [comment]
The feature does not exists at all, so somebody need to implement it. You, or someone else, could submit a patch to add this feature.

I closed this issue because there is no point of leaving it open forever. I won't implement this feature myself, because of lack of time. And it's not very likely that somebody else implement such a "big" feature anytime soon.

**Comment by a3aakash** [comment]
@PowerKiKi thanks for the explanation. I am newbie to these things but I will try locally if I also get the time and I have posted the comment because I urgently needed this feature to deploy for my client project by which I couldn't able to find the solution. But I got one extension for this library supported by LibXL which is a C++ module. You can also look into it for reference.

**Comment by Co0olCat** [comment]
Images are supported. One can link to image macros -> At the moment when I link macros to image in template -> The link is lost when passed through  PHPOffice/PhpSpreadsheet. Any ideas how to preserve the link? Thank you.

**Comment by Co0olCat** [comment]
Found this workaround: https://www.extendoffice.com/documents/excel/4422-excel-run-macro-from-hyperlink.html

It brings another issue -> enabling macros from downloaded files...
