### ISSUE TITLE
PHP 7.1 constructor issues

### ISSUE THREAD

**Issue by depesr** [PHPOffice/PHPExcel#1112]
I got following error "Methods with the same name as their class wi
ll not be constructors in a future version of PHP; PclZip has a deprecated constructor in phpoffice/phpexcel/Classes/PHPExcel/Shared/PCLZip/pclzip.lib.php:190"

**Comment by PowerKiKi** [comment]
As you can see there are [several bugs with PHP 7.1](https://travis-ci.org/PHPOffice/PhpSpreadsheet/jobs/191519295) that were still not fixed and thus neither PHPExcel, not PhpSpreadsheet is compatible with PHP 7.1. Please consider creating a PR against PhpSpreadsheet develop branch if you are able to find a solution.

I am closing this now because it won't be solved in PHPExcel. But it will be in PhpSpreadsheet.
