### ISSUE TITLE
Taking too much time while reading file with more than 5 Lacs rows with 25 columns

### ISSUE THREAD

**Issue by bharat383** [PHPOffice/PHPExcel#1131]
i want to read the excel file data and convert into json file. i have set high configuration in the server for the memory exception and other. but still when i am trying to read excel file, it takes too much time even i have tried with cronjob on linux server. 

is there any solution for this ? please let me known.

Thanks in advance.

**Comment by PowerKiKi** [comment]
Read this [part of PhpSpreadsheet doc](http://phpspreadsheet.readthedocs.io/en/develop/topics/reading-files/#spreadsheet-reader-options), it is also applicable with PHPExcel (although the namespace names changes, the concepts are identical). This should allow to read only the part that you need.

And also read [about caching](http://phpspreadsheet.readthedocs.io/en/develop/topics/settings/#cell-caching), which may help too.

Finally, try to post question on StackOverflow instead of here.
