### ISSUE TITLE
PHP7 with namespace could not work 'PHPExcel_Writer_Excel2007->save()'

### ISSUE THREAD

**Issue by tacsheaven** [PHPOffice/PHPExcel#1180]
I wrote the below php  on PHP 7.0.15 and PHPExcel 1.8.1:
```php
namespace Myspace;
$excel = new \PHPExcel();
...
$write = new \PHPExcel_Writer_Excel2007($excel);
$write->save(filename);
```

this code causes below error:
> Error: Class 'ZipArchive' not found in path/to/PHPExcel/Classes/PHPExcel/Writer/Excel2007.php:220

Does PHPExcel work with global namespace only?

**Comment by PowerKiKi** [comment]
https://github.com/PHPOffice/PHPExcel/blob/1c8c2379ccf5ab9dd7cb46be965821d22173bcf4/Documentation/markdown/Overview/01-Getting-Started.md#php-complains-about-ziparchive-not-being-found

**Comment by tacsheaven** [comment]
I tried...

```PHP
\PHPExcel_Settings::setZipClass(\PHPExcel_Settings::ZIPARCHIVE);
$excel = new \PHPExcel()
...
```
don't work. causes same error.

```PHP
\PHPExcel_Settings::setZipClass(\PHPExcel_Settings::PCLZIP);
$excel = new \PHPExcel();
...
```
is worked correctly.

on namespace, don't use ZIPARCHIVE?

**Comment by PowerKiKi** [comment]
There is no relation with namespace.

If you use `\PHPExcel_Settings::setZipClass(\PHPExcel_Settings::ZIPARCHIVE);`, then you **must** install PHP zip extension and it will work, otherwise it will fail as you saw.

If you cannot, or don't want to, install PHP zip extension, then the only choice you have is to use built-in PCLZIP like you did in second example.
