### ISSUE TITLE
Change homepage in packagist

### ISSUE THREAD

**Issue by tomasfejfar** [PHPOffice/PHPExcel#1192]
Currently on https://packagist.org/packages/phpoffice/phpexcel there is **Homepage** link to http://phpexcel.codeplex.com/ that is marked obsolete.

**Comment by PowerKiKi** [comment]
PHPExcel itself will be obsoleted by PhpSpreadsheet soon. I don't think it's worth the change, but thanks for letting us know.

@MarkBaker or @Progi1984, could you please add a second person to that package on packagist and also https://packagist.org/packages/phpoffice/phpspreadsheet, so that we are sure that there is always somebody who can edit it ?
