### ISSUE TITLE
unix format XLS

### ISSUE THREAD

**Issue by ychoucha** [PHPOffice/PHPExcel#1253]
Hello there, 
i m using PHP exell to convert CSV files to XLS Office format files, 

my problém is the format of the files, i need to have a Unix (LF) format, but phpExcel create a Macintosh (CR) format, how export a :

what i need :
![image](https://user-images.githubusercontent.com/301074/27945547-c76663b2-62ed-11e7-864c-a853ca94386c.png)

What PhpExcell Create : 

![image](https://user-images.githubusercontent.com/301074/27945554-d204ac02-62ed-11e7-9067-862855128010.png)

can we change this formet when i save my XLS files please ?

thanks

**Comment by PowerKiKi** [comment]
XLS is a binary format and thus end of lines are not relevant. XLS files created by PHPExcel work on all OS with all major software (including LibreOffice).

**Comment by ychoucha** [comment]
Hello, 
of cours works with all major software, but we need o way to change the line format

i m still stuck with that

i have to open my files with libreOffice and savez the files in XLS format to change the UNIX stuff line.

can we make it direct with PHPExcel ?

**Comment by PowerKiKi** [comment]
It means you must not do anything with end of line. And it is not possible with PHPExcel to do what you want, because it would break the file.

**Comment by MarkBaker** [comment]
XLS files don't have a line ending format, so PHPExcel doesn't have any option to change something that doesn't exist.... nor can I understand what your actual problem is, because you're original question seems to be missing some information, such as what PHPExcel actually creates compared with what you want to create. A sample csv file that causes your problem so we can try to replicate it would also help

**Comment by ychoucha** [comment]
thanks to you

the way is, 

when u create XLS files with PHPExell, and when u edit the files created with notepad++ u can see the end of line is Macintosh (CR) , and this is my problem.
![image](https://user-images.githubusercontent.com/301074/27955950-9f1558da-6317-11e7-823b-023f4e403bf6.png)

but when u create a XLS files with libreOffice (using it in windows 10)
So the XLS files editing in notepad++ says the files is UNIX (LF) 
![image](https://user-images.githubusercontent.com/301074/27955956-a8e6c79a-6317-11e7-9ff6-d46dd50318f9.png)


i need some PHPExcell files with UNix (LF) files and not Macintosh (CR).

thanks

**Comment by MarkBaker** [comment]
Where do you see the line endings in the binary xls file? It's a binary format, not a flat file format with line endings, so what Notepad++ says should be completely irrelevant.... xls files are never intended to be displayed in a text editor, but in an application that actually parses the binary format.

I'm still completely unclear about your problem.... what happens when you open this XLS file in MS Excel, or in OpenOffice? Does it display correctly there?

**Comment by ychoucha** [comment]
Yes th files works perftcly in Microsoft EXCELL or libreOffice.

**Comment by PowerKiKi** [comment]
I think the real question here is why do you try to vewi/edit a XLS file with a text editor ?
