### ISSUE TITLE
"Autofilter must be set on a range of cells" for seemingly valid file

### ISSUE THREAD

**Issue by Archelyst** [PHPOffice/PHPExcel#459]
I have an .xlsx file from a customer which cannot be loaded by PHPExcel. I'm getting an Exception: Autofilter must be set on a range of cells.

The file can be opened with Excel and Open/LibreOffice without problems. I can provide such a failing file.

**Comment by Raiden89n** [comment]
Hello everybody,
yesterday I got the same exception and I found out that the problem was that the .xslx file I was trying to read had only one filter in one column. It throws that Exception because the function setRange() located in PHPExcel/Worksheet/Autofilter.php doesn't handle that case if you load the .xlsx this way:
```
$inputFileType = PHPExcel_IOFactory::identify($fileName);
$objReader = PHPExcel_IOFactory::createReader($inputFileType);
$objPHPExcel = $objReader->load($fileName);
```
It automatically passes to setRange the value 'H1' which of course is NOT a range.
So the solution I came up with is to change this piece of code in setRange() from: 

```
if (strpos($pRange,':') !== FALSE) {
  $this->_range = $pRange;
} elseif(empty($pRange)) {
    $this->_range = '';
} else {
    throw new PHPExcel_Exception('Autofilter must be set on a range of cells.');

```
to:
```
if (strpos($pRange,':') !== FALSE) {
  $this->_range = $pRange;
} elseif(empty($pRange)) {
    $this->_range = '';
} elseif(!empty($pRange)){
    $this->_range = $pRange.':'.$pRange;
} else {
    throw new PHPExcel_Exception('Autofilter must be set on a range of cells.');
}
```
In this way the function compose a range of one column automatically.
I know this is a spartan solution, but it worked for me :)

Bye bye
