### ISSUE TITLE
Reading date saved as a formula that returns a string

### ISSUE THREAD

**Issue by danielocdh** [PHPOffice/PHPExcel#682]
Hello I have a cell (A2) that is returning a date value correctly on Excel, like this:
A1: 2010
A2: ="10/30/" & A1

A2 is date formatted and it shows:
10/30/2010

I have other cells that relay on A2 to make calculations, the formulas are working correctly on Excel, as they read the value of A2 as a number 40481, PHPExcel is reading the value of A2 as a string "10/30/2010", I tried with both getOldCalculatedValue and getCalculatedValue.

Is there a way to force PHPExcel to behave like excel does when reading the document?

I can not use a fix for the specific cell, because the document might change in the future, but still use these kind of dates.

Thanks

**Comment by MarkBaker** [comment]
Because the result of that calculation is simply a string containing `10/30/2010`. PHPExcel doesn't know that you're treating it as a date elsewhere, and the calculation doesn't read the styling of a cell to know that you've applied a date style to that cell... to be honest, I'm surprised that MS Excel treats it as a date rather than as a string, because (regardless of any format) it is simply a string.

If you're using it in other formulae elsewhere, then the DATE() function will convert that string to a date

**Comment by danielocdh** [comment]
I understand and I'm also surprised.
Using the DATE() function was my suggestion too, thanks for answering.
