### ISSUE TITLE
get Fatal error: Class 'PHPExcel\Writer\BaseWriter' not found 

### ISSUE THREAD

**Issue by ccng** [PHPOffice/PHPExcel#684]
Hi,

I have try use version 1.9 and test with the Example simple.php and found the error as below:
Fatal error: Class 'PHPExcel\Writer\BaseWriter' not found  .....  PHPExcel-1.9/PhpSpreadsheet/Writer/Excel2007.php on line 30

I cannot find teh BaseWriter class in any file under PhpSpreadsheet.

Thanks,
C.C.

**Comment by MarkBaker** [comment]
Don't use the 1.9 branch yet..... not everything has yet been namespaced, so there will be files not found, it's subject to major changes at any time as I refactor it..... it's here because if my development laptop breaks, at least I have this branch as a backup.

It should not be considered as code for anybody to run until such time as I remove the big notice from the README file that says "Don't run this"
