### ISSUE TITLE
CSV Dates Written Differently Depending on Reader File Format

### ISSUE THREAD

**Issue by ComputerTinker** [PHPOffice/PHPExcel#698]
I've created a very simple php script which reads in either an XLSX or XLS file, and then exports the file content to CSV. Here's the guts of the program, which you've seen many times before:

```php
$objReader = PHPExcel_IOFactory::createReader($cExcelFileType);
$objSpreadsheet = $objReader->load($cExcelFileName);
$objWriter = PHPExcel_IOFactory::createWriter($objSpreadsheet, "CSV");
$objWriter->save($cCsvFileName);
```

What's interesting is that if I read in an XLS file and then output a CSV, dates are written in dd/mm/yyyy format as expected. However, if I read in an XLSX file and output a CSV, the dates are written out as integers.  I would have expected the CSV file to be written out using date strings regardless of the import format.

**Comment by ComputerTinker** [comment]
Googled on this a bit and found some people suggesting:
```php
$objReader->setReadDataOnly(false);
```
but that does not fix my issue.

**Comment by MarkBaker** [comment]
It's a highly unusual issue: the number is likely to be the MS Excel serialized timestamp (the number of days since 1st January 1900, or 1st January 1904 if the file was created using the Mac calendar) which is how the date is stored in Excel files. MS Excel uses a number format mask to render it in a human readable format.

PHPExcel holds the value as that MS Excel serialized value internally, and renders it as a date using the number format mask when you write it to a format like CSV, so you should see the human readable date in the CSV unless PHPExcel doesn't have the number format mask

Setting ReadDataOnly to true (the default is always false) means that PHPExcel won't read the number format mask, only the raw data value (the MS Excel serialized datetime value), and can't even tell if the value is a date or not without that mask; which is what makes it the most likely explanation for being unable to convert the value to a human readable date/tie on writing CSV.

What puzzles me is why PHPExcel might be reading the serialized timestamp values, but nor the number format information if ReadDataOnly is set to false. Is it possible for you to attach a file that demonstrates this problem?

**Comment by ComputerTinker** [comment]
Github is not letting me attach files to this issue at the moment, so I just emailed them to the email address shown on your profile.  The "Date Issue.xlsx" file is a stripped down and sanitized version of the file I'm trying to work with, provided to me by my client. The "Date OK.xls" was created simply by saving the file with a different format.  I'm using Office 2013.

**Comment by MarkBaker** [comment]
On 09/10/2015 20:40, Russ wrote:
>
> I've created a very simple php script which reads in either an XLSX or 
> XLS file, and then exports the file content to CSV. Here's the guts of 
> the program, which you've seen many times before:
>
> $objReader = PHPExcel_IOFactory::createReader($cExcelFileType);
> $objSpreadsheet = $objReader->load($cExcelFileName);
> $objWriter = PHPExcel_IOFactory::createWriter($objSpreadsheet, "CSV");
> $objWriter->save($cCsvFileName);
>
> What's interesting is that if I read in an XLS file and then output a 
> CSV, dates are written in dd/mm/yyyy format as expected. However, if I 
> read in an XLSX file and output a CSV, the dates are written out as 
> integers. I would have expected the CSV file to be written out using 
> date strings regardless of the import format.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PHPOffice/PHPExcel/issues/698>.
>
An annoying problem.... a patch that I'd done to handle badly-formed 
xlsx files that were generated by scripts that overrode the pre-defined 
number format masks below 164 (that are reserved for Microsoft internal 
use)... except that my patch broke any use of those pre-defined formats.

Hopefully the change that I've just pushed to the 1.8 branch should fix 
the problem.

-- 
Mark Baker

  _________
|.  \     \-3
|_J_/ PHP |
|| |  __  |
|| |m|  |m|

  I LOVE PHP

**Comment by ComputerTinker** [comment]
Thanks for the quick response on this, I appreciate the patch. I'll give it shot tomorrow and let you know how it works out.

**Comment by ComputerTinker** [comment]
Just tried out the fix and it works perfectly. Thanks again.

**Comment by MarkBaker** [comment]
Thanks for the confirmation, I'll merge the 1.8. branch into develop later this evening

**Comment by hmishra1234** [comment]
Dear Sir 
I am facing the same issue ....the converted .csv file contains number instead of date..could u plz send me the patch as well. 
my sample code is as following..
-----------------------------------------
 $objReader = PHPExcel_IOFactory::createReader($fileType);
    $objReader->setReadDataOnly(false);   
    $objPHPExcel = $objReader->load($infile);  

    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'CSV');
    $objWriter->save($outfile);

-------------------------------------------------
 Thanks

**Comment by MarkBaker** [comment]
MS Excel stores dates as a float, the number of days since 1st January 1900 (a bit like a unix timestamp is a number), and uses a number format mask to identify that it should be displayed as a date/time.

You see your line in your code that reads
```
    $objReader->setReadDataOnly(false);
```

That line specifically tells PHPExcel __not__ to read any formatting information (such as the number format mask that converts an Excel timestamp number into a formatted string) but only to read the raw cell data

That means PHPExcel can't know whether a cell contains a "date" or a "number", so it can only treat it as a number.

Remove that one line of code, it will magically start recognising the values as dates again

**Comment by hmishra1234** [comment]
Dear Sir 
Thanks for the quick response.
When i removed this line 
$objReader->setReadDataOnly(false);


The converted .csv file is completely empty. Don't know why this is happening

**Comment by MarkBaker** [comment]
No, nor do I.... and I'm not likely to be able to guess. I have no idea what filetype you're loading, or what it really contains; so you're giving me no clues to try and figure it out either

Hijacking a closed question isn't a good way of asking either

**Comment by hmishra1234** [comment]
Dear Sir,
I have data in excell format from telephone exchange, i have to convert it into .csv and upload on to mysql db, so that individual user can see their telephone bill accordingly

**Comment by hmishra1234** [comment]
and when i remove this line
$objReader->setReadDataOnly(false);

the converted .csv file is of 0kb size
