### ISSUE TITLE
Infinite looping on SimpleXMLElement in PHPExcel2007.php

### ISSUE THREAD

**Issue by mborgraeve** [PHPOffice/PHPExcel#747]
Hello, 

Please see https://stackoverflow.com/questions/33895476/infinite-loop-in-foreach-on-a-simplexmlelement, where i asked for help on a SimpleXMLElement infinite looping.
It seems that looping on a SimpleXMLElement can cause an infinite loop.
All details are available in the link.

Many thanks for your great work !

**Comment by MarkBaker** [comment]
Can you provide a file that actually demonstrates this SimpleXML infinite loop bug?

**Comment by mborgraeve** [comment]
Yes, I can, but i would rather send it by email (or any sharing medium) to you, as it will contain some business data that i don't want on the web. How would you prefer to receive the file ?
I updated my problem on stackoverflow. It seem to depend on the file, as well as the presence/absence of a breaking point, but i definitely see that the $k key does not get updated after the second iteration while stepping the code.

**Comment by gekannt** [comment]
Could you  please then just modify your data? I feel I got into the same problem

**Comment by mborgraeve** [comment]
Hello,
I'm really sorry, but i can't reproduce it now that i have made some modifications, both in my eclipse config and application...
The problem does not appear to occur anymore, not in debug nor in usual config.

I'll sure let you know if i encounter it again !

Best wishes for 2016 !

**Comment by gekannt** [comment]
Cool, 
I still can reproduce it.

If I read excel file in the following way:

  $phpExcel = new PHPExcel;
  $fileType = PHPExcel_IOFactory::identify($fileTempName);
  $reader = PHPExcel_IOFactory::createReader($fileType);
  $objPHPExcel = $reader->load($fileTempName);
 $data = $objPHPExcel->getActiveSheet()->toArray();

PHP runs out of memory limit consuming all available RAM (nearly 8GB on the development machine).
Though excel file looks pretty ok.

I "fixed" it by messing a bit with  toArray( ) function.
Now I call it in the following way:
$data = $objPHPExcel->getActiveSheet()->toArray(null, false, false);


And it's new implementation is:
	public function toArray($nullValue = null, $calculateFormulas = true, $formatData = true, $returnCellRef = false) {
        // Garbage collect...
                                    
        $this->garbageCollect();

        
        //    Identify the range that we need to extract from the worksheet
        $maxCol = $this->getHighestColumn();
        
        if (strlen($maxCol) > 2) {                        
            $maxCol = PriceGenerator::EXCEL_MAX_COLUMN; // ZZ
        }
        
        
        $maxRow = $this->getHighestRow();
        
        $maxRow = $maxRow > PriceGenerator::EXCEL_MAX_ROW ?  PriceGenerator::EXCEL_MAX_ROW : $maxRow; // 20000

        
        // Return
		return $this->rangeToArray('A1:'.$maxCol.$maxRow,
									$nullValue, $calculateFormulas, $formatData, $returnCellRef);
                
    }

I do understand that this is not applicable in general case.
But it does work in my particular case because I know some limits in advance.


I guess the problem is that PHPExcel somehow supposed non-existing cells to be existing  and make it to loop forever.

**Comment by TaronSaribekyan** [comment]
Problem connected with method **`getHighestColumn()`**. It calculates all columns in sheet _even thay haven't any data, but has some styling_ (e.g. default fixed with). If you will try to get highest column ( `$objPHPExcel->getActiveSheet()->getHighestColumn()`) you will see big number (e.g. AMK), which often happens when .xlsx document created with LibreOffice.
To solve that problem you can do one of such methods:

1. fix you excel file ("remove" all empty columns/rows)
2. instead of `$data = $objPHPExcel->getActiveSheet()->toArray()` use `$data = $objPHPExcel->getActiveSheet()->rangeToArray('A1:'.$objPHPExcel->getActiveSheet()->getHighestDataColumn().$objPHPExcel->getActiveSheet()->getHighestDataRow())`

Methods **`getHighestDataColumn()`** and **`getHighestDataRow()`** are more slow, but they calculate only non empty columns/rows

**Comment by gekannt** [comment]
Unfortunately  I can't try this solution now. Will it work if for example  file contains 50 filled rows , then 20 empty rows  and 10 filles rows again?      

By the way  in my case  a workaround was possible - after getting 1000-2000  empty rows (which have no data inside) I assume there are no data anymore in file and stop reading.

**Comment by TaronSaribekyan** [comment]
I'm not sure that provided by me solution will work for empty rows in the middle of document. But if you sure that document can not have empty columns (not rows) in the middle, you can use `getHighestDataColumn()` and `getHighestRow()` at least to reduce memory usage.

**Comment by gekannt** [comment]
yep, I got it, thanks
