### ISSUE TITLE
PHP7 Uniform Variable Syntax

### ISSUE THREAD

**Issue by rdoursenaud** [PHPOffice/PHPExcel#818]
I believe you have a bug with PHP 7 caused by backward incompatible changes introduced with the ["Uniform Variable Syntax"](https://wiki.php.net/rfc/uniform_variable_syntax#backward_incompatible_changes).

I've published a condensed example in the following gist to help understanding the behavior differences: https://gist.github.com/rdoursenaud/224ac8dff52518402cc5

The offending file is `Classes/PHPExcel/Worksheet/Column.php`.

The following regex `->\$\w+\[` may help you find other occurrences.

**Comment by roger21** [comment]
Yes, this is a real concern, PHPExcel cannot be compatible with PHP7 (at least) because of that

all the code lines:

'class::$foo['bar']
'$variable->$foo['bar']

must be fixed into:

'class::{$foo['bar']}
'$variable->{$foo['bar']}

according to this http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect

i used the following grep commands :

'grep -riP -- '->\$[a-zA-Z0-9]+\[' *
'grep -riP -- '::\$[a-zA-Z0-9]+\[' *

**Comment by PowerKiKi** [comment]
Migrate to PhpSpreadsheet.
