### ISSUE TITLE
Zip extension is required to read a simple .csv file

### ISSUE THREAD

**Issue by marcosgdf** [PHPOffice/PHPExcel#889]
Version: 1.8.1

In requirements, php_zip extension is required only for .ods, .xls, .xlsx files, but an error is thrown if I try to read a simple .csv without it.

```php
				$file['tmp_name']  = 'abc.csv';

				try {
					$excelfd = PHPExcel_IOFactory::load($file['tmp_name']);
				} catch (PHPExcel_Reader_Exception $e) {
					throw new Exception($e->getMessage());
				}
```

```
( ! ) Fatal error: Class 'ZipArchive' not found in lib/phpoffice/phpexcel/Classes/PHPExcel/Reader/Excel2007.php on line 94
```

**Comment by MarkBaker** [comment]
Unless you specify a Reader, PHPExcel tries to identify the file to figure out which Reader to use to load it, testing each format in turn until it finds a match, and defaulting to CSV if it doesn't find any, because there is no signature that can identify a file as csv format.

This means that it needs to use php_zip to check whether the file could be ods, xlsx, etc first (note that xls is not a zip-based format); and if php_zip is not available, then it will fail.

With modern versions of PHP, zip would normally be included by default, and has to have been explicitly disabled for it not to be present. If it isn't, then you can fall back to the PCLZip alternative, configuring PHP to use that before executing the load.

Alternatively, if you know that the file in question is a csv file, then you can specify to use the CSV Reader explicitly, rather than relying on PHPExcel to identify the format first (which is an overhead anyway)

**Comment by marcosgdf** [comment]
That makes much more sense than I thought.

Thanks for the explanation.
