### ISSUE TITLE
1.8.1.0 could not be found.

### ISSUE THREAD

**Issue by egroj55** [PHPOffice/PHPExcel#904]
Hi, trying to add more required files to a symfony2 project, but I get this error. Worked fine for about a week ago I believe. Also the Github page says that the build are failing, both master and dev.

Is there a bug?

`  Problem 1
    - The requested package phpoffice/phpexcel == 1.8.1.0 could not be found.
  Problem 2
    - liuggio/ExcelBundle v2.0.4 requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.x-dev].
    - liuggio/ExcelBundle v2.0.4 requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.x-dev].
    - liuggio/ExcelBundle v2.0.4 requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.x-dev].
    - Can only install one of: phpoffice/phpexcel[dev-master, 1.8.x-dev].
    - Installation request for phpoffice/phpexcel dev-master -> satisfiable by phpoffice/phpexcel[dev-master].
    - Installation request for liuggio/excelbundle == 2.0.4.0 -> satisfiable by liuggio/ExcelBundle[v2.0.4].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.`

**Comment by MarkBaker** [comment]
There is no package `1.8.1.0`, the latest release is `1.8.1`.

And yes builds are failing, because PHPExcel doesn't yet pass all tests...... TDD, test and then write the code to pass those tests.... PHPExcel still fails some of the edge cases tests.... but if we didn't release until every single test passed, then there wouldn't be any releases.... with each release, it passes more of those tests, but isn't yet 100% perfect

**Comment by egroj55** [comment]
Ok, thanks for the explanation.
Changed to "phpoffice/phpexcel": "^1.8",
Works great!
