### ISSUE TITLE
Gaufrette

### ISSUE THREAD

**Issue by wodka** [PHPOffice/PHPExcel#989]
Hi, 

is there a way to change the lib in a way that it is able to open files on "dynamic" file systems?
http://knplabs.github.io/Gaufrette/

I'd like to open something like this: gaufrette://s3/mybucket/test.xlsx (registered streamwrapper)

right now it only works if I create a local copy of the file.

**Comment by Quix0r** [comment]
Can't you maybe use FUSE or equivalents? Then you could simulate a "local" access.

**Comment by MarkBaker** [comment]
Native speadsheet formats require the ability to move the file pointer backward and forward through the file using functions like fseek(), because the actual content is not organised linearly in the file, and not all file streams support fseek, I'm not aware of any remote streams that do support seeking

**Comment by Quix0r** [comment]
@MarkBaker yes, correct. :-) That is why I have recommended FUSE to @wodka where the "special" file system can be wrapped through it.

**Comment by PowerKiKi** [comment]
It seems it can't be fixed, at least not in PHPExcel itself, so closing this issue.

**Comment by wodka** [comment]
Hi, fuse won't help in my case because the file system information (if it be S3 / FTP / etc) is stored in a database and can change frequently. But thanks for pointing out that this cannot work :/

I'll stay with my "create a local copy" approach.
